import { sveltekit } from "@sveltejs/kit/vite";
import tailwindcss from "@tailwindcss/vite";
import { defineConfig } from "vitest/config";

export default defineConfig({
	plugins: [tailwindcss(), sveltekit()],
	test: {
		environment: "node",
		include: ["src/**/*.{test,spec}.{js,ts}"],
		exclude: ["src/**/*.svelte.{test,spec}.{js,ts}"],
		coverage: {
			provider: "istanbul",
			reporter: ["text", "html"],
			include: ["src/lib/**"],
			exclude: [
				"src/lib/**/*.{test,spec}.{js,ts}",
				"src/lib/**/index.ts",
				"src/lib/**/fixtures.ts",
				// Generated by the Paraglide vite plugin.
				"src/lib/paraglide/**",
				// Test-only WCAG helper; not imported by the app.
				"src/lib/contrast.ts",
				"src/lib/presentation/**",
				// Vendored wasm-bindgen glue + the .wasm binary and its thin
				// browser adapter: generated / browser-only, not unit-tested here.
				"src/lib/wasm/**",
			],
			thresholds: {
				"src/lib/domain/**": {
					branches: 100,
					functions: 100,
					lines: 100,
					statements: 100,
				},
				"src/lib/application/**": {
					branches: 100,
					functions: 100,
					lines: 100,
					statements: 100,
				},
				"src/lib/infrastructure/**": {
					// Boundary layer keeps unreachable defensive branches
					// (noUncheckedIndexedAccess `?? ""`, out-of-spec guards),
					// so branches/statements are relaxed to 90%.
					branches: 90,
					functions: 100,
					lines: 100,
					statements: 90,
				},
			},
		},
	},
});
